
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPopupMenu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author AYBUKE KECECI KANMAZ
 */
public class CalculationScreen extends javax.swing.JFrame {
    
    final JPopupMenu menu = new JPopupMenu("Menu");

    /**
     * Creates new form CalculationScreen
     */
    public CalculationScreen() {
        initComponents();
        
        menu.add("TR").addActionListener((e) -> {
            LanguageManager.setLanguage("tr");
            updateTexts();
        });
        menu.add("EN").addActionListener((e) -> {
            LanguageManager.setLanguage("en");
            updateTexts();
        });
        
        resultLabel.setText(LanguageManager.getText("result"));
        this.setTitle(LanguageManager.getText("resultScreen"));
        backButton.setText(LanguageManager.getText("returnHome"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settings = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        bagging_PercentageText = new javax.swing.JTextField();
        bagging_ClassText = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        settings.setText(bundle.getString("CalculationScreen.settings.text")); // NOI18N
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        getContentPane().add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 40, 40));

        resultLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(0, 64, 64));
        resultLabel.setText(bundle.getString("CalculationScreen.resultLabel.text")); // NOI18N
        resultLabel.setToolTipText(bundle.getString("CalculationScreen.resultLabel.toolTipText")); // NOI18N
        getContentPane().add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        bagging_PercentageText.setEditable(false);
        bagging_PercentageText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bagging_PercentageText.setForeground(new java.awt.Color(0, 64, 64));
        getContentPane().add(bagging_PercentageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 115, -1));

        bagging_ClassText.setEditable(false);
        bagging_ClassText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bagging_ClassText.setForeground(new java.awt.Color(0, 64, 64));
        getContentPane().add(bagging_ClassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 115, -1));

        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 64, 64));
        backButton.setText(bundle.getString("CalculationScreen.backButton.text")); // NOI18N
        backButton.setToolTipText(bundle.getString("CalculationScreen.backButton.toolTipText")); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 200, 42));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hospital-background-1952.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 516, 463));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        FileOperation io = new FileOperation();
        try {
            io.createAddHeader();
            DemographicScreen dem = new DemographicScreen();
            ImageIcon img = new ImageIcon("src\\images\\dem_.png");
            dem.setIconImage(img.getImage());
            dem.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(CalculationScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        menu.show(settings, settings.getWidth() / 2, settings.getHeight() / 2);
    }//GEN-LAST:event_settingsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculationScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculationScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    public javax.swing.JTextField bagging_ClassText;
    public javax.swing.JTextField bagging_PercentageText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel settings;
    // End of variables declaration//GEN-END:variables

    private void updateTexts() {
        resultLabel.setText(LanguageManager.getText("result"));
        this.setTitle(LanguageManager.getText("resultScreen"));
        backButton.setText(LanguageManager.getText("returnHome"));
    }
}
